clear all
cd /home/meg/Data/Maor/PhD_SAM/AllSubsSAMfiles
conds = {'LIT', 'CM', 'NM', 'UR'};
grp = {'sz', 'sz', 'sz', 'sz', 'sz', 'sz', 'sz', 'sz', 'sz', 'sz', 'con', 'con',...
    'con', 'con', 'con', 'con', 'con', 'con', 'con', 'con', 'con', 'con', 'con', 'con'};

for i = 1:340
    [~,grpIndx]=sort(rand(1,24));
    [~,condIndx]=sort(rand(4,24));
    
    eval(['!echo "3dMVM -prefix comp1premut',num2str(i),' -jobs 6 -model group -wsVars semantic -num_glt 0 '...
    '-dataTable Subj group semantic InputFile '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(1,1)},' sz2/LITcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(2,1)},' sz2/CMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(3,1)},' sz2/NMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(4,1)},' sz2/URcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(1,2)},' sz3/LITcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(2,2)},' sz3/CMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(3,2)},' sz3/NMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(4,2)},' sz3/URcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(1,3)},' sz4/LITcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(2,3)},' sz4/CMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(3,3)},' sz4/NMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(4,3)},' sz4/URcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(1,4)},' sz5/LITcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(2,4)},' sz5/CMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(3,4)},' sz5/NMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(4,4)},' sz5/URcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(1,5)},' sz6/LITcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(2,5)},' sz6/CMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(3,5)},' sz6/NMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(4,5)},' sz6/URcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(1,6)},' sz7/LITcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(2,6)},' sz7/CMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(3,6)},' sz7/NMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(4,6)},' sz7/URcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(1,7)},' sz9/LITcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(2,7)},' sz9/CMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(3,7)},' sz9/NMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(4,7)},' sz9/URcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(1,8)},' sz12/LITcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(2,8)},' sz12/CMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(3,8)},' sz12/NMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(4,8)},' sz12/URcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(1,9)},' sz13/LITcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(2,9)},' sz13/CMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(3,9)},' sz13/NMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(4,9)},' sz13/URcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(1,10)},' sz15/LITcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(2,10)},' sz15/CMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(3,10)},' sz15/NMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(4,10)},' sz15/URcomp1sz+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(1,11)},' con13/LITcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(2,11)},' con13/CMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(3,11)},' con13/NMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(4,11)},' con13/URcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(1,12)},' con14/LITcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(2,12)},' con14/CMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(3,12)},' con14/NMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(4,12)},' con14/URcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(1,13)},' con15/LITcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(2,13)},' con15/CMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(3,13)},' con15/NMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(4,13)},' con15/URcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(1,14)},' con16/LITcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(2,14)},' con16/CMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(3,14)},' con16/NMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(4,14)},' con16/URcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(1,15)},' con17/LITcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(2,15)},' con17/CMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(3,15)},' con17/NMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(4,15)},' con17/URcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(1,16)},' con18/LITcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(2,16)},' con18/CMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(3,16)},' con18/NMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(4,16)},' con18/URcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(1,17)},' con19/LITcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(2,17)},' con19/CMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(3,17)},' con19/NMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(4,17)},' con19/URcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(1,18)},' con20/LITcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(2,18)},' con20/CMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(3,18)},' con20/NMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(4,18)},' con20/URcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(1,19)},' con21/LITcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(2,19)},' con21/CMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(3,19)},' con21/NMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(4,19)},' con21/URcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(1,20)},' con23/LITcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(2,20)},' con23/CMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(3,20)},' con23/NMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(4,20)},' con23/URcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(1,21)},' con25/LITcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(2,21)},' con25/CMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(3,21)},' con25/NMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(4,21)},' con25/URcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(1,22)},' con27/LITcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(2,22)},' con27/CMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(3,22)},' con27/NMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(4,22)},' con27/URcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(1,23)},' con28/LITcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(2,23)},' con28/CMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(3,23)},' con28/NMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(4,23)},' con28/URcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(1,24)},' con29/LITcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(2,24)},' con29/CMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(3,24)},' con29/NMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(4,24)},' con29/URcomp1con+tlrc" >> mvmPermutcomp1A']);
end

for i = 341:670
    [~,grpIndx]=sort(rand(1,24));
    [~,condIndx]=sort(rand(4,24));
    
    eval(['!echo "3dMVM -prefix comp1premut',num2str(i),' -jobs 6 -model group -wsVars semantic -num_glt 0 '...
    '-dataTable Subj group semantic InputFile '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(1,1)},' sz2/LITcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(2,1)},' sz2/CMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(3,1)},' sz2/NMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(4,1)},' sz2/URcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(1,2)},' sz3/LITcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(2,2)},' sz3/CMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(3,2)},' sz3/NMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(4,2)},' sz3/URcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(1,3)},' sz4/LITcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(2,3)},' sz4/CMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(3,3)},' sz4/NMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(4,3)},' sz4/URcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(1,4)},' sz5/LITcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(2,4)},' sz5/CMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(3,4)},' sz5/NMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(4,4)},' sz5/URcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(1,5)},' sz6/LITcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(2,5)},' sz6/CMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(3,5)},' sz6/NMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(4,5)},' sz6/URcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(1,6)},' sz7/LITcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(2,6)},' sz7/CMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(3,6)},' sz7/NMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(4,6)},' sz7/URcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(1,7)},' sz9/LITcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(2,7)},' sz9/CMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(3,7)},' sz9/NMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(4,7)},' sz9/URcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(1,8)},' sz12/LITcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(2,8)},' sz12/CMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(3,8)},' sz12/NMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(4,8)},' sz12/URcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(1,9)},' sz13/LITcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(2,9)},' sz13/CMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(3,9)},' sz13/NMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(4,9)},' sz13/URcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(1,10)},' sz15/LITcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(2,10)},' sz15/CMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(3,10)},' sz15/NMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(4,10)},' sz15/URcomp1sz+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(1,11)},' con13/LITcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(2,11)},' con13/CMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(3,11)},' con13/NMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(4,11)},' con13/URcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(1,12)},' con14/LITcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(2,12)},' con14/CMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(3,12)},' con14/NMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(4,12)},' con14/URcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(1,13)},' con15/LITcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(2,13)},' con15/CMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(3,13)},' con15/NMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(4,13)},' con15/URcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(1,14)},' con16/LITcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(2,14)},' con16/CMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(3,14)},' con16/NMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(4,14)},' con16/URcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(1,15)},' con17/LITcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(2,15)},' con17/CMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(3,15)},' con17/NMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(4,15)},' con17/URcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(1,16)},' con18/LITcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(2,16)},' con18/CMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(3,16)},' con18/NMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(4,16)},' con18/URcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(1,17)},' con19/LITcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(2,17)},' con19/CMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(3,17)},' con19/NMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(4,17)},' con19/URcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(1,18)},' con20/LITcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(2,18)},' con20/CMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(3,18)},' con20/NMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(4,18)},' con20/URcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(1,19)},' con21/LITcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(2,19)},' con21/CMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(3,19)},' con21/NMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(4,19)},' con21/URcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(1,20)},' con23/LITcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(2,20)},' con23/CMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(3,20)},' con23/NMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(4,20)},' con23/URcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(1,21)},' con25/LITcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(2,21)},' con25/CMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(3,21)},' con25/NMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(4,21)},' con25/URcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(1,22)},' con27/LITcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(2,22)},' con27/CMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(3,22)},' con27/NMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(4,22)},' con27/URcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(1,23)},' con28/LITcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(2,23)},' con28/CMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(3,23)},' con28/NMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(4,23)},' con28/URcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(1,24)},' con29/LITcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(2,24)},' con29/CMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(3,24)},' con29/NMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(4,24)},' con29/URcomp1con+tlrc" >> mvmPermutcomp1B']);
end

for i = 671:1000
    [~,grpIndx]=sort(rand(1,24));
    [~,condIndx]=sort(rand(4,24));
    
    eval(['!echo "3dMVM -prefix comp1premut',num2str(i),' -jobs 6 -model group -wsVars semantic -num_glt 0 '...
    '-dataTable Subj group semantic InputFile '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(1,1)},' sz2/LITcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(2,1)},' sz2/CMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(3,1)},' sz2/NMcomp1sz+tlrc '...
    'sub1 ',grp{grpIndx(1)},' ', conds{condIndx(4,1)},' sz2/URcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(1,2)},' sz3/LITcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(2,2)},' sz3/CMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(3,2)},' sz3/NMcomp1sz+tlrc '...
    'sub2 ',grp{grpIndx(2)},' ', conds{condIndx(4,2)},' sz3/URcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(1,3)},' sz4/LITcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(2,3)},' sz4/CMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(3,3)},' sz4/NMcomp1sz+tlrc '...
    'sub3 ',grp{grpIndx(3)},' ', conds{condIndx(4,3)},' sz4/URcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(1,4)},' sz5/LITcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(2,4)},' sz5/CMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(3,4)},' sz5/NMcomp1sz+tlrc '...
    'sub4 ',grp{grpIndx(4)},' ', conds{condIndx(4,4)},' sz5/URcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(1,5)},' sz6/LITcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(2,5)},' sz6/CMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(3,5)},' sz6/NMcomp1sz+tlrc '...
    'sub5 ',grp{grpIndx(5)},' ', conds{condIndx(4,5)},' sz6/URcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(1,6)},' sz7/LITcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(2,6)},' sz7/CMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(3,6)},' sz7/NMcomp1sz+tlrc '...
    'sub6 ',grp{grpIndx(6)},' ', conds{condIndx(4,6)},' sz7/URcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(1,7)},' sz9/LITcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(2,7)},' sz9/CMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(3,7)},' sz9/NMcomp1sz+tlrc '...
    'sub7 ',grp{grpIndx(7)},' ', conds{condIndx(4,7)},' sz9/URcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(1,8)},' sz12/LITcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(2,8)},' sz12/CMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(3,8)},' sz12/NMcomp1sz+tlrc '...
    'sub8 ',grp{grpIndx(8)},' ', conds{condIndx(4,8)},' sz12/URcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(1,9)},' sz13/LITcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(2,9)},' sz13/CMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(3,9)},' sz13/NMcomp1sz+tlrc '...
    'sub9 ',grp{grpIndx(9)},' ', conds{condIndx(4,9)},' sz13/URcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(1,10)},' sz15/LITcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(2,10)},' sz15/CMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(3,10)},' sz15/NMcomp1sz+tlrc '...
    'sub10 ',grp{grpIndx(10)},' ', conds{condIndx(4,10)},' sz15/URcomp1sz+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(1,11)},' con13/LITcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(2,11)},' con13/CMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(3,11)},' con13/NMcomp1con+tlrc '...
    'sub11 ',grp{grpIndx(11)},' ', conds{condIndx(4,11)},' con13/URcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(1,12)},' con14/LITcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(2,12)},' con14/CMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(3,12)},' con14/NMcomp1con+tlrc '...
    'sub12 ',grp{grpIndx(12)},' ', conds{condIndx(4,12)},' con14/URcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(1,13)},' con15/LITcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(2,13)},' con15/CMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(3,13)},' con15/NMcomp1con+tlrc '...
    'sub13 ',grp{grpIndx(13)},' ', conds{condIndx(4,13)},' con15/URcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(1,14)},' con16/LITcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(2,14)},' con16/CMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(3,14)},' con16/NMcomp1con+tlrc '...
    'sub14 ',grp{grpIndx(14)},' ', conds{condIndx(4,14)},' con16/URcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(1,15)},' con17/LITcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(2,15)},' con17/CMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(3,15)},' con17/NMcomp1con+tlrc '...
    'sub15 ',grp{grpIndx(15)},' ', conds{condIndx(4,15)},' con17/URcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(1,16)},' con18/LITcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(2,16)},' con18/CMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(3,16)},' con18/NMcomp1con+tlrc '...
    'sub16 ',grp{grpIndx(16)},' ', conds{condIndx(4,16)},' con18/URcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(1,17)},' con19/LITcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(2,17)},' con19/CMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(3,17)},' con19/NMcomp1con+tlrc '...
    'sub17 ',grp{grpIndx(17)},' ', conds{condIndx(4,17)},' con19/URcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(1,18)},' con20/LITcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(2,18)},' con20/CMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(3,18)},' con20/NMcomp1con+tlrc '...
    'sub18 ',grp{grpIndx(18)},' ', conds{condIndx(4,18)},' con20/URcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(1,19)},' con21/LITcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(2,19)},' con21/CMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(3,19)},' con21/NMcomp1con+tlrc '...
    'sub19 ',grp{grpIndx(19)},' ', conds{condIndx(4,19)},' con21/URcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(1,20)},' con23/LITcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(2,20)},' con23/CMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(3,20)},' con23/NMcomp1con+tlrc '...
    'sub20 ',grp{grpIndx(20)},' ', conds{condIndx(4,20)},' con23/URcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(1,21)},' con25/LITcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(2,21)},' con25/CMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(3,21)},' con25/NMcomp1con+tlrc '...
    'sub21 ',grp{grpIndx(21)},' ', conds{condIndx(4,21)},' con25/URcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(1,22)},' con27/LITcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(2,22)},' con27/CMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(3,22)},' con27/NMcomp1con+tlrc '...
    'sub22 ',grp{grpIndx(22)},' ', conds{condIndx(4,22)},' con27/URcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(1,23)},' con28/LITcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(2,23)},' con28/CMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(3,23)},' con28/NMcomp1con+tlrc '...
    'sub23 ',grp{grpIndx(23)},' ', conds{condIndx(4,23)},' con28/URcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(1,24)},' con29/LITcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(2,24)},' con29/CMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(3,24)},' con29/NMcomp1con+tlrc '...
    'sub24 ',grp{grpIndx(24)},' ', conds{condIndx(4,24)},' con29/URcomp1con+tlrc" >> mvmPermutcomp1C']);
end


%%
% take only voxels in the cortex
cd /home/meg/Data/Maor/PhD_SAM/AllSubsSAMfiles/MVMpermutsComp1
for i=1:1000
    eval(['masktlrc(''comp1premut',num2str(i),'+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    disp(i);
end;

for i=1:1000
    % read max F value
    eval(['!~/abin/3dBrickStat -max comp1premut',num2str(i),'_ctx+tlrc''[1]'' >> FmaxGrp.txt']);
    eval(['!~/abin/3dBrickStat -max comp1premut',num2str(i),'_ctx+tlrc''[2]'' >> FmaxSem.txt']);
    eval(['!~/abin/3dBrickStat -max comp1premut',num2str(i),'_ctx+tlrc''[3]'' >> FmaxInt.txt']);
    % compute volume of largest positive clusters
    eval(['!~/abin/3dclust -quiet -1clip 4.303 5 125 comp1premut',num2str(i),'_ctx+tlrc''[1]''+tlrc > posClustGrp.txt'])
    eval(['!~/abin/3dclust -quiet -1clip 2.745 5 125 comp1premut',num2str(i),'_ctx+tlrc''[2]''+tlrc > posClustSem.txt'])
    eval(['!~/abin/3dclust -quiet -1clip 2.745 5 125 comp1premut',num2str(i),'_ctx+tlrc''[3]''+tlrc > posClustInt.txt'])
    posClustGrp=importdata('posClustGrp.txt');
    posClustSem=importdata('posClustSem.txt');
    posClustInt=importdata('posClustInt.txt');
    if iscell(posClustGrp)
        posClustGrpSize=0;
    else
        posClustGrpSize=posClustGrp(1)/125;
    end
    if iscell(posClustSem)
        posClustSemSize=0;
    else
        posClustSemSize=posClustSem(1)/125;
    end  
    if iscell(posClustInt)
        posClustIntSize=0;
    else
        posClustIntSize=posClustInt(1)/125;
    end  
    clustGrpSize(i)=posClustGrpSize;
    clustSemSize(i)=posClustSemSize;
    clustIntSize(i)=posClustIntSize;    
    !rm *ClustGrp.txt
    !rm *ClustSem.txt
    !rm *ClustInt.txt
end

% find critical values
clustGrpSize=sort(clustGrpSize,'descend');
clustSemSize=sort(clustSemSize,'descend');
clustIntSize=sort(clustIntSize,'descend');

FmaxGrp=importdata('FmaxGrp.txt');
FmaxSem=importdata('FmaxSem.txt');
FmaxInt=importdata('FmaxInt.txt');

FmaxGrp=sort(FmaxGrp,'descend');
FmaxSem=sort(FmaxSem,'descend');
FmaxInt=sort(FmaxInt,'descend');

FcritGrp = FmaxGrp(50);
FcritSem = FmaxSem(50);
FcritInt = FmaxInt(50);
clustSizeCritGrp = clustGrpSize(50);
clustSizeCritSem = clustSemSize(50);
clustSizeCritInt = clustIntSize(50);

save comp1permutCrit_Size_F FcritGrp FcritSem FcritInt clustSizeCritGrp clustSizeCritSem clustSizeCritInt

!rm FmaxGrp.txt
!rm FmaxSem.txt
!rm FmaxInt.txt
