clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Comp3_19subs_Permuts
conds = {'102', '104', '106', '108'};

for i = 1:340
    [~,condIndx]=sort(rand(4,19));
    
    eval(['!echo "3dANOVA3 -type 4 -alevels 2 -blevels 2 -clevels 19 '...
    '-dset 1 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(1,1)},'Comp3MS+tlrc '...
    '-dset 1 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(1,2)},'Comp3MS+tlrc '...
    '-dset 1 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(1,3)},'Comp3MS+tlrc '...
    '-dset 1 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(1,4)},'Comp3MS+tlrc '...
    '-dset 1 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(1,5)},'Comp3MS+tlrc '...
    '-dset 1 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(1,6)},'Comp3MS+tlrc '...
    '-dset 1 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(1,7)},'Comp3MS+tlrc '...
    '-dset 1 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(1,8)},'Comp3MS+tlrc '...
    '-dset 1 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(1,9)},'Comp3MS+tlrc '...
    '-dset 1 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(1,10)},'Comp3MS+tlrc '...
    '-dset 1 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(1,11)},'Comp3MS+tlrc '...
    '-dset 1 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(1,12)},'Comp3MS+tlrc '...
    '-dset 1 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(1,13)},'Comp3MS+tlrc '...
    '-dset 1 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(1,14)},'Comp3MS+tlrc '...
    '-dset 1 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(1,15)},'Comp3MS+tlrc '...
    '-dset 1 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(1,16)},'Comp3MS+tlrc '...
    '-dset 1 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(1,17)},'Comp3MS+tlrc '...
    '-dset 1 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(1,18)},'Comp3MS+tlrc '...
    '-dset 1 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(1,19)},'Comp3MS+tlrc '...
    '-dset 1 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(2,1)},'Comp3MS+tlrc '...
    '-dset 1 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(2,2)},'Comp3MS+tlrc '...
    '-dset 1 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(2,3)},'Comp3MS+tlrc '...
    '-dset 1 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(2,4)},'Comp3MS+tlrc '...
    '-dset 1 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(2,5)},'Comp3MS+tlrc '...
    '-dset 1 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(2,6)},'Comp3MS+tlrc '...
    '-dset 1 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(2,7)},'Comp3MS+tlrc '...
    '-dset 1 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(2,8)},'Comp3MS+tlrc '...
    '-dset 1 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(2,9)},'Comp3MS+tlrc '...
    '-dset 1 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(2,10)},'Comp3MS+tlrc '...
    '-dset 1 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(2,11)},'Comp3MS+tlrc '...
    '-dset 1 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(2,12)},'Comp3MS+tlrc '...
    '-dset 1 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(2,13)},'Comp3MS+tlrc '...
    '-dset 1 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(2,14)},'Comp3MS+tlrc '...
    '-dset 1 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(2,15)},'Comp3MS+tlrc '...
    '-dset 1 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(2,16)},'Comp3MS+tlrc '...
    '-dset 1 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(2,17)},'Comp3MS+tlrc '...
    '-dset 1 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(2,18)},'Comp3MS+tlrc '...
    '-dset 1 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(2,19)},'Comp3MS+tlrc '...
    '-dset 2 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(3,1)},'Comp3MS+tlrc '...
    '-dset 2 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(3,2)},'Comp3MS+tlrc '...
    '-dset 2 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(3,3)},'Comp3MS+tlrc '...
    '-dset 2 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(3,4)},'Comp3MS+tlrc '...
    '-dset 2 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(3,5)},'Comp3MS+tlrc '...
    '-dset 2 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(3,6)},'Comp3MS+tlrc '...
    '-dset 2 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(3,7)},'Comp3MS+tlrc '...
    '-dset 2 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(3,8)},'Comp3MS+tlrc '...
    '-dset 2 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(3,9)},'Comp3MS+tlrc '...
    '-dset 2 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(3,10)},'Comp3MS+tlrc '...
    '-dset 2 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(3,11)},'Comp3MS+tlrc '...
    '-dset 2 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(3,12)},'Comp3MS+tlrc '...
    '-dset 2 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(3,13)},'Comp3MS+tlrc '...
    '-dset 2 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(3,14)},'Comp3MS+tlrc '...
    '-dset 2 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(3,15)},'Comp3MS+tlrc '...
    '-dset 2 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(3,16)},'Comp3MS+tlrc '...
    '-dset 2 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(3,17)},'Comp3MS+tlrc '...
    '-dset 2 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(3,18)},'Comp3MS+tlrc '...
    '-dset 2 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(3,19)},'Comp3MS+tlrc '...
    '-dset 2 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(4,1)},'Comp3MS+tlrc '...
    '-dset 2 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(4,2)},'Comp3MS+tlrc '...
    '-dset 2 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(4,3)},'Comp3MS+tlrc '...
    '-dset 2 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(4,4)},'Comp3MS+tlrc '...
    '-dset 2 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(4,5)},'Comp3MS+tlrc '...
    '-dset 2 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(4,6)},'Comp3MS+tlrc '...
    '-dset 2 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(4,7)},'Comp3MS+tlrc '...
    '-dset 2 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(4,8)},'Comp3MS+tlrc '...
    '-dset 2 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(4,9)},'Comp3MS+tlrc '...
    '-dset 2 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(4,10)},'Comp3MS+tlrc '...
    '-dset 2 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(4,11)},'Comp3MS+tlrc '...
    '-dset 2 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(4,12)},'Comp3MS+tlrc '...
    '-dset 2 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(4,13)},'Comp3MS+tlrc '...
    '-dset 2 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(4,14)},'Comp3MS+tlrc '...
    '-dset 2 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(4,15)},'Comp3MS+tlrc '...
    '-dset 2 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(4,16)},'Comp3MS+tlrc '...
    '-dset 2 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(4,17)},'Comp3MS+tlrc '...
    '-dset 2 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(4,18)},'Comp3MS+tlrc '...
    '-dset 2 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(4,19)},'Comp3MS+tlrc '...
    ' -fa pre_post_permut',num2str(i),' -fb right_left_permut',num2str(i),' -fab prePost_RL_permut',num2str(i),'" >> 3dANOVAHypPermutComp3A']);
end


for i = 341:670
    [~,condIndx]=sort(rand(4,19));
    
    eval(['!echo "3dANOVA3 -type 4 -alevels 2 -blevels 2 -clevels 19 '...
    '-dset 1 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(1,1)},'Comp3MS+tlrc '...
    '-dset 1 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(1,2)},'Comp3MS+tlrc '...
    '-dset 1 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(1,3)},'Comp3MS+tlrc '...
    '-dset 1 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(1,4)},'Comp3MS+tlrc '...
    '-dset 1 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(1,5)},'Comp3MS+tlrc '...
    '-dset 1 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(1,6)},'Comp3MS+tlrc '...
    '-dset 1 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(1,7)},'Comp3MS+tlrc '...
    '-dset 1 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(1,8)},'Comp3MS+tlrc '...
    '-dset 1 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(1,9)},'Comp3MS+tlrc '...
    '-dset 1 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(1,10)},'Comp3MS+tlrc '...
    '-dset 1 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(1,11)},'Comp3MS+tlrc '...
    '-dset 1 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(1,12)},'Comp3MS+tlrc '...
    '-dset 1 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(1,13)},'Comp3MS+tlrc '...
    '-dset 1 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(1,14)},'Comp3MS+tlrc '...
    '-dset 1 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(1,15)},'Comp3MS+tlrc '...
    '-dset 1 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(1,16)},'Comp3MS+tlrc '...
    '-dset 1 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(1,17)},'Comp3MS+tlrc '...
    '-dset 1 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(1,18)},'Comp3MS+tlrc '...
    '-dset 1 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(1,19)},'Comp3MS+tlrc '...
    '-dset 1 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(2,1)},'Comp3MS+tlrc '...
    '-dset 1 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(2,2)},'Comp3MS+tlrc '...
    '-dset 1 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(2,3)},'Comp3MS+tlrc '...
    '-dset 1 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(2,4)},'Comp3MS+tlrc '...
    '-dset 1 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(2,5)},'Comp3MS+tlrc '...
    '-dset 1 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(2,6)},'Comp3MS+tlrc '...
    '-dset 1 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(2,7)},'Comp3MS+tlrc '...
    '-dset 1 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(2,8)},'Comp3MS+tlrc '...
    '-dset 1 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(2,9)},'Comp3MS+tlrc '...
    '-dset 1 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(2,10)},'Comp3MS+tlrc '...
    '-dset 1 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(2,11)},'Comp3MS+tlrc '...
    '-dset 1 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(2,12)},'Comp3MS+tlrc '...
    '-dset 1 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(2,13)},'Comp3MS+tlrc '...
    '-dset 1 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(2,14)},'Comp3MS+tlrc '...
    '-dset 1 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(2,15)},'Comp3MS+tlrc '...
    '-dset 1 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(2,16)},'Comp3MS+tlrc '...
    '-dset 1 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(2,17)},'Comp3MS+tlrc '...
    '-dset 1 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(2,18)},'Comp3MS+tlrc '...
    '-dset 1 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(2,19)},'Comp3MS+tlrc '...
    '-dset 2 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(3,1)},'Comp3MS+tlrc '...
    '-dset 2 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(3,2)},'Comp3MS+tlrc '...
    '-dset 2 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(3,3)},'Comp3MS+tlrc '...
    '-dset 2 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(3,4)},'Comp3MS+tlrc '...
    '-dset 2 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(3,5)},'Comp3MS+tlrc '...
    '-dset 2 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(3,6)},'Comp3MS+tlrc '...
    '-dset 2 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(3,7)},'Comp3MS+tlrc '...
    '-dset 2 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(3,8)},'Comp3MS+tlrc '...
    '-dset 2 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(3,9)},'Comp3MS+tlrc '...
    '-dset 2 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(3,10)},'Comp3MS+tlrc '...
    '-dset 2 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(3,11)},'Comp3MS+tlrc '...
    '-dset 2 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(3,12)},'Comp3MS+tlrc '...
    '-dset 2 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(3,13)},'Comp3MS+tlrc '...
    '-dset 2 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(3,14)},'Comp3MS+tlrc '...
    '-dset 2 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(3,15)},'Comp3MS+tlrc '...
    '-dset 2 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(3,16)},'Comp3MS+tlrc '...
    '-dset 2 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(3,17)},'Comp3MS+tlrc '...
    '-dset 2 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(3,18)},'Comp3MS+tlrc '...
    '-dset 2 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(3,19)},'Comp3MS+tlrc '...
    '-dset 2 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(4,1)},'Comp3MS+tlrc '...
    '-dset 2 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(4,2)},'Comp3MS+tlrc '...
    '-dset 2 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(4,3)},'Comp3MS+tlrc '...
    '-dset 2 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(4,4)},'Comp3MS+tlrc '...
    '-dset 2 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(4,5)},'Comp3MS+tlrc '...
    '-dset 2 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(4,6)},'Comp3MS+tlrc '...
    '-dset 2 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(4,7)},'Comp3MS+tlrc '...
    '-dset 2 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(4,8)},'Comp3MS+tlrc '...
    '-dset 2 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(4,9)},'Comp3MS+tlrc '...
    '-dset 2 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(4,10)},'Comp3MS+tlrc '...
    '-dset 2 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(4,11)},'Comp3MS+tlrc '...
    '-dset 2 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(4,12)},'Comp3MS+tlrc '...
    '-dset 2 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(4,13)},'Comp3MS+tlrc '...
    '-dset 2 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(4,14)},'Comp3MS+tlrc '...
    '-dset 2 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(4,15)},'Comp3MS+tlrc '...
    '-dset 2 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(4,16)},'Comp3MS+tlrc '...
    '-dset 2 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(4,17)},'Comp3MS+tlrc '...
    '-dset 2 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(4,18)},'Comp3MS+tlrc '...
    '-dset 2 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(4,19)},'Comp3MS+tlrc '...
    ' -fa pre_post_permut',num2str(i),' -fb right_left_permut',num2str(i),' -fab prePost_RL_permut',num2str(i),'" >> 3dANOVAHypPermutComp3B']);
end


for i = 671:1000
    [~,condIndx]=sort(rand(4,19));
    
    eval(['!echo "3dANOVA3 -type 4 -alevels 2 -blevels 2 -clevels 19 '...
    '-dset 1 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(1,1)},'Comp3MS+tlrc '...
    '-dset 1 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(1,2)},'Comp3MS+tlrc '...
    '-dset 1 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(1,3)},'Comp3MS+tlrc '...
    '-dset 1 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(1,4)},'Comp3MS+tlrc '...
    '-dset 1 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(1,5)},'Comp3MS+tlrc '...
    '-dset 1 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(1,6)},'Comp3MS+tlrc '...
    '-dset 1 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(1,7)},'Comp3MS+tlrc '...
    '-dset 1 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(1,8)},'Comp3MS+tlrc '...
    '-dset 1 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(1,9)},'Comp3MS+tlrc '...
    '-dset 1 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(1,10)},'Comp3MS+tlrc '...
    '-dset 1 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(1,11)},'Comp3MS+tlrc '...
    '-dset 1 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(1,12)},'Comp3MS+tlrc '...
    '-dset 1 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(1,13)},'Comp3MS+tlrc '...
    '-dset 1 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(1,14)},'Comp3MS+tlrc '...
    '-dset 1 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(1,15)},'Comp3MS+tlrc '...
    '-dset 1 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(1,16)},'Comp3MS+tlrc '...
    '-dset 1 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(1,17)},'Comp3MS+tlrc '...
    '-dset 1 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(1,18)},'Comp3MS+tlrc '...
    '-dset 1 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(1,19)},'Comp3MS+tlrc '...
    '-dset 1 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(2,1)},'Comp3MS+tlrc '...
    '-dset 1 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(2,2)},'Comp3MS+tlrc '...
    '-dset 1 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(2,3)},'Comp3MS+tlrc '...
    '-dset 1 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(2,4)},'Comp3MS+tlrc '...
    '-dset 1 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(2,5)},'Comp3MS+tlrc '...
    '-dset 1 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(2,6)},'Comp3MS+tlrc '...
    '-dset 1 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(2,7)},'Comp3MS+tlrc '...
    '-dset 1 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(2,8)},'Comp3MS+tlrc '...
    '-dset 1 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(2,9)},'Comp3MS+tlrc '...
    '-dset 1 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(2,10)},'Comp3MS+tlrc '...
    '-dset 1 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(2,11)},'Comp3MS+tlrc '...
    '-dset 1 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(2,12)},'Comp3MS+tlrc '...
    '-dset 1 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(2,13)},'Comp3MS+tlrc '...
    '-dset 1 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(2,14)},'Comp3MS+tlrc '...
    '-dset 1 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(2,15)},'Comp3MS+tlrc '...
    '-dset 1 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(2,16)},'Comp3MS+tlrc '...
    '-dset 1 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(2,17)},'Comp3MS+tlrc '...
    '-dset 1 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(2,18)},'Comp3MS+tlrc '...
    '-dset 1 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(2,19)},'Comp3MS+tlrc '...
    '-dset 2 1 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(3,1)},'Comp3MS+tlrc '...
    '-dset 2 1 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(3,2)},'Comp3MS+tlrc '...
    '-dset 2 1 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(3,3)},'Comp3MS+tlrc '...
    '-dset 2 1 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(3,4)},'Comp3MS+tlrc '...
    '-dset 2 1 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(3,5)},'Comp3MS+tlrc '...
    '-dset 2 1 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(3,6)},'Comp3MS+tlrc '...
    '-dset 2 1 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(3,7)},'Comp3MS+tlrc '...
    '-dset 2 1 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(3,8)},'Comp3MS+tlrc '...
    '-dset 2 1 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(3,9)},'Comp3MS+tlrc '...
    '-dset 2 1 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(3,10)},'Comp3MS+tlrc '...
    '-dset 2 1 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(3,11)},'Comp3MS+tlrc '...
    '-dset 2 1 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(3,12)},'Comp3MS+tlrc '...
    '-dset 2 1 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(3,13)},'Comp3MS+tlrc '...
    '-dset 2 1 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(3,14)},'Comp3MS+tlrc '...
    '-dset 2 1 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(3,15)},'Comp3MS+tlrc '...
    '-dset 2 1 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(3,16)},'Comp3MS+tlrc '...
    '-dset 2 1 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(3,17)},'Comp3MS+tlrc '...
    '-dset 2 1 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(3,18)},'Comp3MS+tlrc '...
    '-dset 2 1 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(3,19)},'Comp3MS+tlrc '...
    '-dset 2 2 1 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(4,1)},'Comp3MS+tlrc '...
    '-dset 2 2 2 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(4,2)},'Comp3MS+tlrc '...
    '-dset 2 2 3 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(4,3)},'Comp3MS+tlrc '...
    '-dset 2 2 4 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(4,4)},'Comp3MS+tlrc '...
    '-dset 2 2 5 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(4,5)},'Comp3MS+tlrc '...
    '-dset 2 2 6 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(4,6)},'Comp3MS+tlrc '...
    '-dset 2 2 7 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(4,7)},'Comp3MS+tlrc '...
    '-dset 2 2 8 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(4,8)},'Comp3MS+tlrc '...
    '-dset 2 2 9 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(4,9)},'Comp3MS+tlrc '...
    '-dset 2 2 10 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(4,10)},'Comp3MS+tlrc '...
    '-dset 2 2 11 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(4,11)},'Comp3MS+tlrc '...
    '-dset 2 2 12 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(4,12)},'Comp3MS+tlrc '...
    '-dset 2 2 13 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(4,13)},'Comp3MS+tlrc '...
    '-dset 2 2 14 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(4,14)},'Comp3MS+tlrc '...
    '-dset 2 2 15 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(4,15)},'Comp3MS+tlrc '...
    '-dset 2 2 16 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(4,16)},'Comp3MS+tlrc '...
    '-dset 2 2 17 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(4,17)},'Comp3MS+tlrc '...
    '-dset 2 2 18 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(4,18)},'Comp3MS+tlrc '...
    '-dset 2 2 19 /home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(4,19)},'Comp3MS+tlrc '...
    ' -fa pre_post_permut',num2str(i),' -fb right_left_permut',num2str(i),' -fab prePost_RL_permut',num2str(i),'" >> 3dANOVAHypPermutComp3C']);
end

% take only voxels in the cortex for the interaction (main effects are not
% interesting)
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Comp3_19subs_Permuts
for i=1:1000
    eval(['masktlrc(''prePost_RL_permut',num2str(i),'+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    disp(i);
end;

for i=1:1000
    % read max F value
    eval(['!~/abin/3dBrickStat -max prePost_RL_permut',num2str(i),'_ctx+tlrc >> FmaxInt.txt']);
    % compute volume of largest positive clusters
    eval(['!~/abin/3dclust -quiet -1clip 4.417 5 125 prePost_RL_permut',num2str(i),'_ctx+tlrc''[1]'' > posClustInt.txt'])
    posClustInt=importdata('posClustInt.txt');
    if iscell(posClustInt)
        posClustIntSize=0;
    else
        posClustIntSize=posClustInt(1)/125;
    end  
    clustIntSize(i)=posClustIntSize;    
    !rm *ClustInt.txt
end

% find critical values
clustIntSize=sort(clustIntSize,'descend');
FmaxInt=importdata('FmaxInt.txt');
FmaxInt=sort(FmaxInt,'descend');
FcritInt = FmaxInt(50);
clustSizeCritInt = clustIntSize(50);

save comp3permutCrit_Size_F FcritInt clustSizeCritInt

!rm FmaxInt.txt


%% permutations for the t-tests
% 102 - PreR
% 104 - PreL
% 106 - PostR
% 108 - PostL
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Comp3New19Subs/ttestPermut
% -------------------------------------------------------------------
%                       for left hand
% -------------------------------------------------------------------
conds = {'104', '108'};

for i = 1:1000
    [~,condIndx]=sort(rand(2,19));
    eval(['!echo "3dttest -prefix 3dttestPermutL',num2str(i),' -set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(1,1)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(1,2)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(1,3)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(1,4)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(1,5)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(1,6)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(1,7)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(1,8)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(1,9)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(1,10)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(1,11)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(1,12)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(1,13)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(1,14)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(1,15)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(1,16)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(1,17)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(1,18)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(1,19)},'Comp3MS+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(2,1)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(2,2)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(2,3)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(2,4)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(2,5)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(2,6)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(2,7)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(2,8)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(2,9)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(2,10)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(2,11)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(2,12)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(2,13)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(2,14)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(2,15)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(2,16)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(2,17)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(2,18)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(2,19)},'Comp3MS+tlrc ">> 3dttest1000permutL']);
end
% -------------------------------------------------------------------
%                       for right hand
% -------------------------------------------------------------------
conds = {'102', '106'};

for i = 1:1000
    [~,condIndx]=sort(rand(2,19));
    eval(['!echo "3dttest -prefix 3dttestPermutR',num2str(i),' -set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(1,1)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(1,2)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(1,3)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(1,4)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(1,5)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(1,6)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(1,7)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(1,8)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(1,9)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(1,10)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(1,11)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(1,12)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(1,13)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(1,14)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(1,15)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(1,16)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(1,17)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(1,18)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(1,19)},'Comp3MS+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',conds{condIndx(2,1)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',conds{condIndx(2,2)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',conds{condIndx(2,3)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',conds{condIndx(2,4)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',conds{condIndx(2,5)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',conds{condIndx(2,6)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',conds{condIndx(2,7)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',conds{condIndx(2,8)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',conds{condIndx(2,9)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',conds{condIndx(2,10)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',conds{condIndx(2,11)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',conds{condIndx(2,12)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',conds{condIndx(2,13)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',conds{condIndx(2,14)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',conds{condIndx(2,15)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',conds{condIndx(2,16)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',conds{condIndx(2,17)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',conds{condIndx(2,18)},'Comp3MS+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',conds{condIndx(2,19)},'Comp3MS+tlrc ">> 3dttest1000permutR']);
end

% take only voxels in the cortex
for i=1:1000
    eval(['masktlrc(''3dttestPermutL',num2str(i),'+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    eval(['masktlrc(''3dttestPermutR',num2str(i),'+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    disp(i);
end;

% creat a list of all sig clusters volumes
ClustL_Size=[];
ClustL_Size=[];
ClustR_Size=[];
ClustR_Size=[];
for i=1:1000
    % compute volume
    eval(['!~/abin/3dclust -quiet -2thresh -2.341 2.341 5 125 3dttestPermutL',num2str(i),'_ctx+tlrc''[1]'' > ClustL.txt'])
    eval(['!~/abin/3dclust -quiet -2thresh -2.341 2.341 5 125 3dttestPermutR',num2str(i),'_ctx+tlrc''[1]'' > ClustR.txt'])
    ClustL=importdata('ClustL.txt');
    ClustR=importdata('ClustR.txt');
    
    if isempty(ClustL)
        ClustL_Size=[ClustL_Size; 0];
    elseif iscell(ClustL)
        ClustL_Size=[ClustL_Size; 0];
    else
        ClustL_Size=[ClustL_Size; ClustL(:,1)./125];
    end
        
    if isempty(ClustR)
        ClustR_Size=[ClustR_Size; 0];
    elseif iscell(ClustR)
        ClustR_Size=[ClustR_Size; 0];
    else
        ClustR_Size=[ClustR_Size; ClustR(:,1)./125];
    end

    !rm *ClustL.txt
    !rm *ClustR.txt
    
    disp(sprintf('%d / 1000', i));
end;

% find critical values
ClustL_Size=sort(ClustL_Size,'descend');
ClustR_Size=sort(ClustR_Size,'descend');
ClustSizeCritL = ClustL_Size(50);
ClustSizeCritR = ClustR_Size(50);
save clustSizeCrit

%% permutation for the sig clusters only - Mean Ts
for i=1:1000
    eval(['!3dcalc -prefix 3dttestPermutL',num2str(i),'_mask_ctx -a Clust8_PreL_PostL_p0.25_mask+tlrc -b 3dttestPermutL',num2str(i),'_ctx+tlrc''[1]'' -exp "b*ispositive(a)"']);
    eval(['!3dcalc -prefix 3dttestPermutR',num2str(i),'_mask_ctx -a Clust8_PreR_PostR_p0.25_mask+tlrc -b 3dttestPermutR',num2str(i),'_ctx+tlrc''[1]'' -exp "b*ispositive(a)"']);
    disp(sprintf('%d / 1000', i));
end;

for i=1:1000
    eval(['!~/abin/3dBrickStat -absolute -mean 3dttestPermutL',num2str(i),'_mask_ctx+tlrc >> TmeanL.txt']);
    eval(['!~/abin/3dBrickStat -absolute -mean 3dttestPermutR',num2str(i),'_mask_ctx+tlrc >> TmeanR.txt']);
    disp(sprintf('%d/1000', i));
end;

TmeanL=importdata('TmeanL.txt');
TmeanR=importdata('TmeanR.txt');
TmeanL=sort(TmeanL,'descend');
TmeanR=sort(TmeanR,'descend');
TmeanL_CritV = TmeanL(50);
TmeanR_CritV = TmeanR(50);

% results: Tcrit_L = 0.0019
%          Tcrit_R = 0.0011
%% T-permutation for all voxels
for i=1:1000
    eval(['!~/abin/3dBrickStat -absolute -mean 3dttestPermutL',num2str(i),'_ctx+tlrc''[1]'' >> TmeanAllL.txt']);
    eval(['!~/abin/3dBrickStat -absolute -mean 3dttestPermutR',num2str(i),'_ctx+tlrc''[1]'' >> TmeanAllR.txt']);
    disp(sprintf('%d/1000', i));
end;

TmeanAllL=importdata('TmeanAllL.txt');
TmeanAllR=importdata('TmeanAllR.txt');
TmeanAllL=sort(TmeanAllL,'descend');
TmeanAllR=sort(TmeanAllR,'descend');
TmeanAllL_CritV = TmeanAllL(50);
TmeanAllR_CritV = TmeanAllR(50);

% results: TcritAll_L = 0.2249
%          TcritAll_R = 0.2170

%% T mean permutation for sig clusters only - max Ts
for i=1:1000
    eval(['!~/abin/3dBrickStat -absolute -max 3dttestPermutL',num2str(i),'_mask_ctx+tlrc >> TmaxL.txt']);
    eval(['!~/abin/3dBrickStat -absolute -max 3dttestPermutR',num2str(i),'_mask_ctx+tlrc >> TmaxR.txt']);
    disp(sprintf('%d/1000', i));
end;

TmaxL=importdata('TmaxL.txt');
TmaxR=importdata('TmaxR.txt');
TmaxL=sort(TmaxL,'descend');
TmaxR=sort(TmaxR,'descend');
TmaxL_CritV = TmaxL(50);
TmaxR_CritV = TmaxR(50);

% results: Tcrit_L = 2.7996
%          Tcrit_R = 2.6421

%% T max permutation for all voxels
for i=1:1000
    eval(['!~/abin/3dBrickStat -absolute -max 3dttestPermutL',num2str(i),'_ctx+tlrc''[1]'' >> TmaxAllL.txt']);
    eval(['!~/abin/3dBrickStat -absolute -max 3dttestPermutR',num2str(i),'_ctx+tlrc''[1]'' >> TmaxAllR.txt']);
    disp(sprintf('%d/1000', i));
end;

TmaxAllL=importdata('TmaxAllL.txt');
TmaxAllR=importdata('TmaxAllR.txt');
TmaxAllL=sort(TmaxAllL,'descend');
TmaxAllR=sort(TmaxAllR,'descend');
TmaxAllL_CritV = TmaxAllL(50);
TmaxAllR_CritV = TmaxAllR(50);

% results: Tcrit_L = 3.9744
%          Tcrit_R = 3.9971