%% Permutations for hypnosis t-tests with p < 0.025
clear all
% masking the files so the permutations will run faster
for subs=[7:19 21 22 25:28];
    eval(['cd /home/meg/Data/Maor/Hypnosis/Subjects/Hyp',num2str(subs),'/1_40Hz']);
    for j=[102 104 106 108];
    eval(['masktlrc(''Con',num2str(j),'Comp3MS+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    eval(['masktlrc(''Con',num2str(j),'EarlyComp1MS+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    eval(['masktlrc(''Con',num2str(j),'EarlyComp2MS+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    eval(['masktlrc(''Con',num2str(j),'EarlyComp3MS+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    eval(['masktlrc(''Con',num2str(j),'EarlyComp4MS+tlrc'',''MASKctx+tlrc'',''_ctx'');']);
    end
end

%% Comp3 Left Hand
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[104,108];

for i=1:1000
    [~,indx]=sort(rand(2,17));

    eval(['!echo "3dttest -prefix 3dttestComp3LeftPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,7))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,8))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,9))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,10))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,11))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,12))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,13))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,14))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,15))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,16))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,17))),'Comp3MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,7))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,8))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,9))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,10))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,11))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,12))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,13))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,14))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,15))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,16))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,17))),'Comp3MS_ctx+tlrc" >> 3dttestComp3LeftPermuts']);
end

% finding the critical cluster size
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/Comp3Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestComp3LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeComp3Left.txt']);
    clustSizeComp3Left=importdata('clustSizeComp3Left.txt');
    if iscell(clustSizeComp3Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeComp3Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 42 voxels!!!
% 3 clusters survive it (one in the RH - more activity before hypnosis - and 2 in the
% LH - more activity during hypnosis).

%% Comp3 Right Hand
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[102,106];

for i=1:1000
    [~,indx]=sort(rand(2,17));

    eval(['!echo "3dttest -prefix 3dttestComp3RightPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,7))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,8))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,9))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,10))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,11))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,12))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,13))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,14))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,15))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,16))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,17))),'Comp3MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,7))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,8))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,9))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,10))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,11))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,12))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,13))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,14))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,15))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,16))),'Comp3MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,17))),'Comp3MS_ctx+tlrc" >> 3dttestComp3RightPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/Comp3Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestComp3RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeComp3Right.txt']);
    clustSizeComp3Right=importdata('clustSizeComp3Right.txt');
    if iscell(clustSizeComp3Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeComp3Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 41 voxels!!!
% 3 clusters survive it (2 in the LH and one in the RH in all more activity in the post).

%% Early Comp1 Left
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[104,108];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp1LeftPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp1MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp1MS_ctx+tlrc" >> 3dttestEarlyComp1LeftPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp1Left
clustSizeDistrib=[];
%% Early Comp1 Left

clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[104,108];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp1LeftPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp1MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp1MS_ctx+tlrc" >> 3dttestEarlyComp1LeftPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp1Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp1LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp1Left.txt']);
    clustSizeEarlyComp1Left=importdata('clustSizeEarlyComp1Left.txt');
    if iscell(clustSizeEarlyComp1Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp1Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 34 voxels!!!
% Nothing survives it.

%% Early Comp1 Right
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[102,106];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp1RightPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp1MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp1MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp1MS_ctx+tlrc" >> 3dttestEarlyComp1RightPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp1Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp1RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp1Right.txt']);
    clustSizeEarlyComp1Right=importdata('clustSizeEarlyComp1Right.txt');
    if iscell(clustSizeEarlyComp1Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp1Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 35 voxels!!!
% 2 clusters survived.

%% Early Comp2 Left
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[104,108];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp2LeftPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp2MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp2MS_ctx+tlrc" >> 3dttestEarlyComp2LeftPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp2Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp2LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp2Left.txt']);
    clustSizeEarlyComp2Left=importdata('clustSizeEarlyComp2Left.txt');
    if iscell(clustSizeEarlyComp2Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp2Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 48 voxels!!!

%% Early Comp2 Right
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[102,106];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp2RightPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp2MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp2MS_ctx+tlrc" >> 3dttestEarlyComp2RightPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp2Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp2RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp2Right.txt']);
    clustSizeEarlyComp2Right=importdata('clustSizeEarlyComp2Right.txt');
    if iscell(clustSizeEarlyComp2Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp2Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 35 voxels!!!

%% Early Comp2 Left
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[104,108];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp2LeftPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp2MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp2MS_ctx+tlrc" >> 3dttestEarlyComp2LeftPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp2Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp2LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp2Left.txt']);
    clustSizeEarlyComp2Left=importdata('clustSizeEarlyComp2Left.txt');
    if iscell(clustSizeEarlyComp2Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp2Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 48 voxels!!!

%% Early Comp2 Right
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults

conds=[102,106];

for i=1:1000
    [~,indx]=sort(rand(2,19));

    eval(['!echo "3dttest -prefix 3dttestEarlyComp2RightPermut',num2str(i),' -paired '...
    '-set1 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(1,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(1,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(1,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(1,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(1,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(1,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(1,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(1,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(1,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(1,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(1,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(1,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(1,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(1,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(1,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(1,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(1,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(1,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(1,19))),'EarlyComp2MS_ctx+tlrc '...
    '-set2 '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp7/1_40Hz/Con',num2str(conds(indx(2,1))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp8/1_40Hz/Con',num2str(conds(indx(2,2))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp9/1_40Hz/Con',num2str(conds(indx(2,3))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp10/1_40Hz/Con',num2str(conds(indx(2,4))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp11/1_40Hz/Con',num2str(conds(indx(2,5))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp12/1_40Hz/Con',num2str(conds(indx(2,6))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp13/1_40Hz/Con',num2str(conds(indx(2,7))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp14/1_40Hz/Con',num2str(conds(indx(2,8))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp15/1_40Hz/Con',num2str(conds(indx(2,9))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp16/1_40Hz/Con',num2str(conds(indx(2,10))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp17/1_40Hz/Con',num2str(conds(indx(2,11))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp18/1_40Hz/Con',num2str(conds(indx(2,12))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp19/1_40Hz/Con',num2str(conds(indx(2,13))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp21/1_40Hz/Con',num2str(conds(indx(2,14))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp22/1_40Hz/Con',num2str(conds(indx(2,15))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp25/1_40Hz/Con',num2str(conds(indx(2,16))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp26/1_40Hz/Con',num2str(conds(indx(2,17))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp27/1_40Hz/Con',num2str(conds(indx(2,18))),'EarlyComp2MS_ctx+tlrc '...
    '/home/meg/Data/Maor/Hypnosis/Subjects/Hyp28/1_40Hz/Con',num2str(conds(indx(2,19))),'EarlyComp2MS_ctx+tlrc" >> 3dttestEarlyComp2RightPermuts']);
end

% finding the critical cluster size
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp2Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp2RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp2Right.txt']);
    clustSizeEarlyComp2Right=importdata('clustSizeEarlyComp2Right.txt');
    if iscell(clustSizeEarlyComp2Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp2Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));
% result: cluster size critical value is 39 voxels!!!

%% did the same for EarlyComp3 and EarlyComp4

% Early Comp3 Left
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp3Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp3LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp3Left.txt']);
    clustSizeEarlyComp3Left=importdata('clustSizeEarlyComp3Left.txt');
    if iscell(clustSizeEarlyComp3Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp3Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));

% Early Comp3 Right
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp3Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp3RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp3Right.txt']);
    clustSizeEarlyComp3Right=importdata('clustSizeEarlyComp3Right.txt');
    if iscell(clustSizeEarlyComp3Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp3Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));

% Early Comp4 Left
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp4Left
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp4LeftPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp4Left.txt']);
    clustSizeEarlyComp4Left=importdata('clustSizeEarlyComp4Left.txt');
    if iscell(clustSizeEarlyComp4Left)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp4Left.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));

% Early Comp4 Right
clear all
cd /home/meg/Data/Maor/Hypnosis/SAMresults/Permutations/EarlyComp4Right
clustSizeDistrib=[];

for i=1:1000
    eval(['!~/abin/3dclust -1clip 2.447 5 125 3dttestEarlyComp4RightPermut',num2str(i),'+tlrc''[1]'' > clustSizeEarlyComp4Right.txt']);
    clustSizeEarlyComp4Right=importdata('clustSizeEarlyComp4Right.txt');
    if iscell(clustSizeEarlyComp4Right)
        clustSizeDistrib=[clustSizeDistrib;0];
    else
        clustSizeDistrib=[clustSizeDistrib;clustSizeEarlyComp4Right.data(:,1)./125];
    end
end

clustSize=sort(clustSizeDistrib,'descend');
clustSizeCrit=clustSize(round(length(clustSize)*0.05));